### ISSUE TITLE
verification_tasks design is inflexible and fragile

### ISSUE THREAD

**Issue by delcypher** [delcypher/svcomp-build-mockup#1]
The current schema for `verification_tasks` is.

``` yaml
verification_tasks:
    type: array
    items:
      # FIXME: This doesn't seem flexible enough and is fragile!
      type: string
      enum:
        - "CHECK( init(main()), LTL(G ! call(__VERIFIER_error())) )"
        - "CHECK( init(main()), LTL(G valid-free) )"
        - "CHECK( init(main()), LTL(G valid-deref) )"
        - "CHECK( init(main()), LTL(G valid-memtrack) )"
        - "CHECK( init(main()), LTL(G ! overflow) )"
        - "CHECK( init(main()), LTL(F end) )"
      minItems: 1
```

This really fragile (any spaces and our scheme doesn't validate) and not very flexible. We should probably structure this information or remove the enum requirement. Thoughts?
