### ISSUE TITLE
Does allowing a benchmark specification to declare multiple benchmarks over complicate things?

### ISSUE THREAD

**Issue by delcypher** [delcypher/svcomp-build-mockup#2]
Currently the schema is

``` yaml
  variants:
    # Maps a build variant name to a list of defines.
    # Having multiple build variant names declares multiple variants
    # of the benchmark (the full name is "<name>_<build_variant_name>") that
    # should each be built/verified with their own set of defines.
    # This provides a convenient way to reuse code between benchmarks
    # that have very minor variations (e.g. loop bound)
    type: object
    minProperties: 1
    additionalProperties: false
    patternProperties:
      # The name of a build variant must match this pattern
      "^[a-z0-9_-]+$":
        type: array
        items:
          type: string
          pattern: "^[A-Z][A-Z0-9_]+(=[A-Za-z0-9]+)?$"
```

Having multiple defines e.g.

``` yaml
architecture: x86_64
language:  c99
name: mybenchmark
sources:
  - a.c
  - b.c
variants:
  "single_loop": [ 'LOOP_BOUND=1']
  "really_loopy": [ 'LOOP_BOUND=100']
```

declares two benchmarks with name
- `mybenchmark_single_loop`
- `mybenchmark_really_loopy`

Is this overcomplicating things? I think it's a useful feature but some may disagree.
